source 'https://rubygems.org'
ruby "3.3.0"
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-imagemagick'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'csv'
    gem 'observer'
    gem 'htmlcompressor'
    gem 'htmlbeautifier'
    gem 'jekyll-postcss-v2'
    gem 'nokogiri', '~> 1.16'
end
