#name: Deploy

#on:
#  push:
#    branches:
#      - master
#      - main

#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      # checkout code
#      - uses: actions/checkout@v4
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build site
#        run: |
#          docker container run \
#          --mount type=bind,source="$(pwd)",target="/website" \
#          ghcr.io/vallejosgroup/website
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v4
#       with:
#          # GITHUB_TOKEN secret is set up automatically
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./_site 
